### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Momo90k** [DmitriiFeshchenko/godot-appodeal-editor-plugin#1]
Thank you for your work. The only thing missing is a step by step tutorial and this will be the most perfect Godot monetization plugin ever.

**Comment by dmitriifeshchenko** [comment]
Thanks for your feedback! I will consider adding more detailed docs in the upcoming release.

**Comment by Momo90k** [comment]
Can you please help me with a short step by step list on how to implement rewarded ads with consent forms and everything.
Just the steps not entire paragraphs. I really need your help. It's urgent.
Thank you very much. Appreciate it 👍🏼.

**Comment by dmitriifeshchenko** [comment]
@Momo90k, have you seen the [demo project](https://github.com/DmitriiFeshchenko/godot-appodeal-demo-project/blob/main/demo_scene.gd)? If not, I recommend you look into that project first. Let me know if something is not clear there.
