### ISSUE TITLE
Godot 3 support

### ISSUE THREAD

**Issue by Momo90k** [DmitriiFeshchenko/godot-appodeal-editor-plugin#2]
Hello.
Does this plugin work in Godot 3?

**Comment by dmitriifeshchenko** [comment]
Hi, @Momo90k!

Yes, it does. [The attached plugin](https://github.com/DmitriiFeshchenko/godot-appodeal-editor-plugin/releases/tag/v2.0.0) was built for Godot v3.5.3.
